print('Hello World !')
print('What is your name ?')
name = raw_input()
print('It is good to meet you ' + name)
print ('The lenght of your name is ') 
print len(name)
print ('What is your age ?')
age = raw_input()
print ('You will be ' + str(int(age) + 1) + ' in a year.')
